version: "3.8"
services:
  multiverse_travels_booker:
    container_name: multiverse_travels_booker
    image: api_multiverse_travels_booker
    build:
      context: .
      target: prod
    working_dir: /usr/src/api
    restart: always
    environment:
      - APP_ENV=production # Variável para mudar ambiente do "jennifer ORM"
      - KEMAL_ENV=production # Variável para mudar ambiente do "Kemal"
    ports:
      - 3000:3000
    volumes:
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
    depends_on:
      db_multiverse_travels_booker:
        condition: service_healthy # Deve aguardar o banco ficar operacional
    networks:
      - multiverse_travels_booker

  db_multiverse_travels_booker:
    container_name: db_multiverse_travels_booker
    image: mysql_init_db
    build:
      context: ./db
      target: db_prod
    command: mysqld --default-authentication-plugin=mysql_native_password # Comando necessário para que o "jennifer ORM" conecte-se ao banco dados
    restart: "always"
    environment:
      - MYSQL_ROOT_PASSWORD=root123456
    ports:
      - 3003:3306
    platform: linux/x86_64
    cap_add:
      - SYS_NICE # Deve omitir alertas menores
    volumes:
      - ./db/structure.sql:/usr/src/database/structure.sql
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"] # Deve aguardar o banco ficar operacional
      timeout: 10s
      retries: 5
    networks:
      - multiverse_travels_booker

networks:
  multiverse_travels_booker:
    external: false
    name: multiverse_travels_booker